import time
import turtle


print("Chase's Song")
time.sleep(1)
print("~~~~~~~~~~~~~~~~~~~~~~")
time.sleep(1)
print("THIS IS CHASES SONG!!! IT GOES ON ALL DAY LONG!!!!!!! LONG LONG CHASES SONG!!!!!!")
time.sleep(0.5)
print("YO, MY NAME IS CHASE, I DONT LIKE TO JACE, BUT I AINT NO HACE, IMMMMM CHAASSSSE YYYAAAA")
time.sleep(10)
print("chase's sonnnnggggggg...... it's chases songggggg........ DA END :P")
time.sleep(1)
print("WAIT")
time.sleep(1)
print("thats not it")
time.sleep(1)
print("HEY WHATS UP??")


t = turtle.Pen()


t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.up()
t.forward(100)
t.down()
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.up()
t.forward(200)
t.down()
t.forward(50)
t.left(120)
t.forward(50)
t.left(120)
t.forward(50)
t.up()
t.forward(100)
t.down()
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.right(120)
t.forward(50)
t.right(120)
t.forward(50)
t.up()
t.forward(100)
t.down()
t.begin_fill()
t.forward(10)
t.right(90)
t.forward(10)
t.right(90)
t.forward(10)
t.right(90)
t.forward(10)
t.end_fill()
t.up()
t.forward(100)
t.color(0,1,0)
t.begin_fill()
t.circle(50)
t.end_fill()
t.up()
t.right(90)
t.forward(50)
t.down()
t.circle(1)
t.up()
t.forward(20)
t.down()
t.color(0,0,0)
t.reset()
t.right(90)
t.up()
t.forward(100)
t.down()
t.circle(200)
